#!/bin/bash
# Run this from inside python-import_modules/ directory of your repo

cat > add_0.py << 'EOF'
#!/usr/bin/python3
def add(a, b):
    """My addition function

    Args:
        a: first integer
        b: second integer

    Returns:
        The return value. a + b
    """
    return (a + b)
EOF

cat > 0-add.py << 'EOF'
#!/usr/bin/python3
"""Imports the add function from add_0 and prints the result of 1 + 2"""
from add_0 import add

if __name__ == "__main__":
    a = 1
    b = 2
    print("{} + {} = {}".format(a, b, add(a, b)))
EOF

cat > calculator_1.py << 'EOF'
#!/usr/bin/python3
def add(a, b):
    """My addition function

    Args:
        a: first integer
        b: second integer

    Returns:
        The return value. a + b
    """
    return (a + b)


def sub(a, b):
    """My subtraction function

    Args:
        a: first integer
        b: second integer

    Returns:
        The return value. a - b
    """
    return (a - b)


def mul(a, b):
    """My multiplication function

    Args:
        a: first integer
        b: second integer

    Returns:
        The return value. a * b
    """
    return (a * b)


def div(a, b):
    """My division function

    Args:
        a: first integer
        b: second integer

    Returns:
        The return value. a / b
    """
    return int(a / b)
EOF

cat > 1-calculation.py << 'EOF'
#!/usr/bin/python3
"""Imports add, sub, mul, div from calculator_1 and prints results"""
from calculator_1 import add, sub, mul, div

if __name__ == "__main__":
    a = 10
    b = 5
    print("{} + {} = {}".format(a, b, add(a, b)))
    print("{} - {} = {}".format(a, b, sub(a, b)))
    print("{} * {} = {}".format(a, b, mul(a, b)))
    print("{} / {} = {}".format(a, b, div(a, b)))
EOF

cat > 2-args.py << 'EOF'
#!/usr/bin/python3
"""Prints the number of and the list of script arguments"""
from sys import argv

if __name__ == "__main__":
    n = len(argv) - 1
    if n == 0:
        print("0 arguments.")
    elif n == 1:
        print("1 argument:")
    else:
        print("{} arguments:".format(n))
    for i in range(1, len(argv)):
        print("{}: {}".format(i, argv[i]))
EOF

cat > 3-infinite_add.py << 'EOF'
#!/usr/bin/python3
"""Prints the sum of all script arguments cast to integers"""
from sys import argv

if __name__ == "__main__":
    total = 0
    for arg in argv[1:]:
        total += int(arg)
    print(total)
EOF

cat > 4-hidden_discovery.py << 'EOF'
#!/usr/bin/python3
"""Prints, in alpha order, all names in hidden_4.pyc not starting with __"""

if __name__ == "__main__":
    import hidden_4
    names = sorted(n for n in dir(hidden_4) if not n.startswith("__"))
    for name in names:
        print(name)
EOF

cat > variable_load_5.py << 'EOF'
#!/usr/bin/python3
a = 98
"""Simple variable
"""
EOF

cat > 5-variable_load.py << 'EOF'
#!/usr/bin/python3
"""Imports the variable a from variable_load_5 and prints it"""
from variable_load_5 import a

if __name__ == "__main__":
    print(a)
EOF

cat > README.md << 'EOF'
# python-import_modules

## Description
This project covers Python modules: importing functions and variables
between files, using `sys.argv` to read command-line arguments, and
inspecting a compiled `.pyc` module with `dir()`.

| File | Description |
| --- | --- |
| `add_0.py` | Module defining an `add(a, b)` function |
| `0-add.py` | Imports `add` from `add_0` and prints `1 + 2 = 3` |
| `calculator_1.py` | Module defining `add`, `sub`, `mul`, `div` functions |
| `1-calculation.py` | Imports the calculator functions and prints results for `10` and `5` |
| `2-args.py` | Prints the number and list of arguments passed to the script |
| `3-infinite_add.py` | Prints the sum of all arguments passed to the script |
| `4-hidden_discovery.py` | Prints the public names defined in `hidden_4.pyc`, alphabetically |
| `variable_load_5.py` | Module defining a variable `a = 98` |
| `5-variable_load.py` | Imports `a` from `variable_load_5` and prints it |

## Requirements
- All scripts run on Ubuntu 20.04 LTS with python3 (3.8.5)
- All code follows pycodestyle (2.7.*)
- Every file starts with `#!/usr/bin/python3`
- Every file ends with a new line and is executable
- No file's code executes when imported (guarded by `if __name__ == "__main__":`)

## Note on task 4
`hidden_4.pyc` is not generated by this script. Download it into this
directory before running `4-hidden_discovery.py`:

```
curl -Lso "hidden_4.pyc" "https://github.com/alx-tools/0x02.py/raw/master/hidden_4.pyc"
```

It must be run with Python 3.8.x, since the `.pyc` was compiled with that
version and will not load under a different Python version.
EOF

chmod +x add_0.py 0-add.py calculator_1.py 1-calculation.py 2-args.py \
          3-infinite_add.py 4-hidden_discovery.py variable_load_5.py \
          5-variable_load.py

echo "All files + README.md created and made executable."
echo "Downloading hidden_4.pyc..."
curl -Lso "hidden_4.pyc" "https://github.com/alx-tools/0x02.py/raw/master/hidden_4.pyc"

echo "Running quick sanity checks (must be run with python3.8 for full pass)..."
./0-add.py
./1-calculation.py
./2-args.py
./2-args.py Hello
./2-args.py Hello Welcome To The Best School
./3-infinite_add.py
./3-infinite_add.py 79 10
./3-infinite_add.py 79 10 -40 -300 89
./5-variable_load.py
echo "4-hidden_discovery.py needs python3.8 specifically to run (pyc bytecode is version-locked) - test it in your Ubuntu 20.04 environment."
echo "Done. Review, git add ., git commit, git push."
